### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined   at VocAPI.getDefinition

### ISSUE THREAD

**Issue by vikash423q** [th0rgall/voc-api#3] opened 2020-06-08 18:01 UTC
I am getting this when calling from my react app

**Comment by th0rgall** [comment] 2020-06-08 21:13
Hey Vikash, thanks for reporting this!

Are you using Create React App or another webpack-based react app?

And did you call the method like this?

```
const VocAPI = require("voc-api");
const vocapi = new VocAPI();
vocapi.getDefinition("word").then(<your function>);
```

If yes, then this is probably a bug.

The project has been somewhat unmaintained lately, although I think it still works in the browser extension where I use it.

I hope to find some time to check & fix this in the coming weeks.

**Comment by vikash423q** [comment] 2020-06-08 22:13
Yes, I am using create react app and calling the api exactly as you mentioned.
I am looking forward for the issue to be fixed. Please fix it ASAP.

**Comment by th0rgall** [comment] 2020-07-28 18:04
Hey @vikash423q, I looked at this issue in more detail today; I could reproduce it. The cause was a wrong version of [voc-http](https://github.com/th0rgall/voc-http/), a subproject of this API. I updated the version. It should be fixed now, thanks again for reporting.

Unfortunately though, I realized you can probably not use the API in your React App (or any other regular web app). You will run into [CORS restrictions](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

This API was built for a web extension, an environment that can circumvent CORS restrictions and other browser safety measures. Unless your React app is running inside a web extension background page, it won't work. I clarified this now in the [readme](https://github.com/th0rgall/voc-api/blob/master/readme.md) too.

**Closed as completed by th0rgall** 2020-07-28 18:04 UTC
